export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');

  const { ids } = req.query;
  if (!ids) return res.status(400).json({ valid: [] });

  const url = `https://thumbnails.roblox.com/v1/assets?assetIds=${ids}&returnPolicy=PlaceHolder&size=420x420&format=Png&isCircular=false`;

  try {
    const r = await fetch(url);
    const data = await r.json();

    // an id is valid if it has an imageUrl and it's not a placeholder/blocked image
    const BLOCKED_URLS = [
      'AutoGenerated',
      'no-preview',
      'blocked',
    ];

    const valid = (data.data || [])
      .filter(item => {
        if (!item.imageUrl) return false;
        if (item.state === 'Blocked' || item.state === 'Error') return false;
        for (const b of BLOCKED_URLS) {
          if (item.imageUrl.toLowerCase().includes(b.toLowerCase())) return false;
        }
        return true;
      })
      .map(item => String(item.targetId));

    res.status(200).json({ valid });
  } catch (e) {
    res.status(500).json({ valid: [] });
  }
}